<a href="https://colab.research.google.com/github/amirejaz/API-to-Pandas-Dataset/blob/main/IMDB_TOP5MOVIES_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import requests

In [ ]:
response = requests.get('https://imdb-api.com/en/API/Top250Movies/k_av7stgt7').json()

In [ ]:
for i in response['items']:
  print(i['title'])

The Shawshank Redemption
The Godfather
The Dark Knight
The Godfather Part II
12 Angry Men
Schindler's List
The Lord of the Rings: The Return of the King
Pulp Fiction
The Lord of the Rings: The Fellowship of the Ring
The Good, the Bad and the Ugly
Forrest Gump
Fight Club
Inception
The Lord of the Rings: The Two Towers
Star Wars: Episode V - The Empire Strikes Back
The Matrix
Goodfellas
One Flew Over the Cuckoo's Nest
Se7en
Seven Samurai
It's a Wonderful Life
The Silence of the Lambs
City of God
Saving Private Ryan
Life Is Beautiful
The Green Mile
Interstellar
Star Wars
Terminator 2: Judgment Day
Back to the Future
Spirited Away
Psycho
The Pianist
Léon: The Professional
Parasite
The Lion King
Gladiator
American History X
The Usual Suspects
The Departed
The Prestige
Casablanca
Top Gun: Maverick
Whiplash
The Intouchables
Modern Times
Hara-Kiri
Grave of the Fireflies
Once Upon a Time in the West
Rear Window
Alien
City Lights
Cinema Paradiso
Memento
Apocalypse Now
Indiana Jones and the Raiders of the Lost Ark
Django Unchained
WALL·E
The Lives of Others
Sunset Blvd.
Paths of Glory
The Shining
The Great Dictator
Witness for the Prosecution
Avengers: Infinity War
Aliens
American Beauty
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Spider-Man: Into the Spider-Verse
The Dark Knight Rises
Oldboy
Joker
Amadeus
Braveheart
Toy Story
Coco
The Boat
Inglourious Basterds
Princess Mononoke
Avengers: Endgame
Once Upon a Time in America
Good Will Hunting
Requiem for a Dream
Toy Story 3
Your Name.
Singin' in the Rain
3 Idiots
Star Wars: Episode VI - Return of the Jedi
2001: A Space Odyssey
Eternal Sunshine of the Spotless Mind
Reservoir Dogs
High and Low
Capernaum
Citizen Kane
Lawrence of Arabia
The Hunt
M
North by Northwest
Vertigo
Amélie
A Clockwork Orange
Come and See
Full Metal Jacket
Double Indemnity
The Apartment
Scarface
Ikiru
The Sting
To Kill a Mockingbird
Taxi Driver
L.A. Confidential
Up
Heat
Hamilton
Metropolis
A Separation
Snatch
Die Hard
Incendies
Indiana Jones and the Last Crusade
Bicycle Thieves
1917
Spider-Man: No Way Home
Like Stars on Earth
Downfall
For a Few Dollars More
Batman Begins
Dangal
The Kid
Some Like It Hot
The Father
All About Eve
Green Book
The Wolf of Wall Street
Everything Everywhere All at Once
Judgment at Nuremberg
Unforgiven
Ran
Casino
Pan's Labyrinth
There Will Be Blood
The Sixth Sense
A Beautiful Mind
Monty Python and the Holy Grail
The Truman Show
Yojimbo
The Treasure of the Sierra Madre
Shutter Island
Rashomon
The Great Escape
Jurassic Park
Kill Bill: Vol. 1
No Country for Old Men
Finding Nemo
The Elephant Man
Raging Bull
Chinatown
Gone with the Wind
V for Vendetta
The Thing
Inside Out
Lock, Stock and Two Smoking Barrels
Dial M for Murder
The Secret in Their Eyes
The Bridge on the River Kwai
Howl's Moving Castle
Three Billboards Outside Ebbing, Missouri
Trainspotting
Gran Torino
Warrior
Fargo
My Neighbor Totoro
Prisoners
Million Dollar Baby
The Gold Rush
Blade Runner
Catch Me If You Can
On the Waterfront
The Third Man
Children of Heaven
Ben-Hur
12 Years a Slave
The General
Wild Strawberries
Gone Girl
Before Sunrise
Harry Potter and the Deathly Hallows: Part 2
The Deer Hunter
In the Name of the Father
The Grand Budapest Hotel
Mr. Smith Goes to Washington
The Wages of Fear
Barry Lyndon
Sherlock Jr.
Memories of Murder
Room
Klaus
Hacksaw Ridge
The Seventh Seal
Wild Tales
The Big Lebowski
Mad Max: Fury Road
How to Train Your Dragon
Mary and Max
Monsters, Inc.
Jaws
The Passion of Joan of Arc
Hotel Rwanda
Dead Poets Society
Tokyo Story
Pather Panchali
Rocky
Platoon
Ford v Ferrari
Stand by Me
The Terminator
Spotlight
Rush
Into the Wild
Network
The Wizard of Oz
Logan
Groundhog Day
Ratatouille
Before Sunset
The Exorcist
The Best Years of Our Lives
The Incredibles
To Be or Not to Be
Rebecca
The Battle of Algiers
The Grapes of Wrath
Hachi: A Dog's Tale
Cool Hand Luke
Amores perros
Pirates of the Caribbean: The Curse of the Black Pearl
La Haine
The 400 Blows
Persona
My Father and My Son
Life of Brian
Dersu Uzala
It Happened One Night
The Sound of Music
The Handmaiden
Jai Bhim
Aladdin
Gandhi
The Help
Beauty and the Beast

In [ ]:
title = []
IMDB_Rating = []
Rating_count = []
ranking = []
year = []

for i in response['items']:
  title.append(i['title'])
  try:
    IMDB_Rating.append(i['imDbRating'])
  except:
      IMDB_Rating.append(np.nan)
  Rating_count.append(i['imDbRatingCount'])
  ranking.append(i['rank'])
  year.append(i['year'])

d = {'title': title, 'IMDB_Rating':IMDB_Rating, 'Rating_count':Rating_count, 'ranking':ranking, 'year':year}
df = pd.DataFrame(d)

df

                        title IMDB_Rating Rating_count ranking  year
0    The Shawshank Redemption         9.2      2601582       1  1994
1               The Godfather         9.2      1797052       2  1972
2             The Dark Knight         9.0      2573028       3  2008
3       The Godfather Part II         9.0      1238114       4  1974
4                12 Angry Men         8.9       768576       5  1957
..                        ...         ...          ...     ...   ...
245                  Jai Bhim         8.0       191057     246  2021
246                   Aladdin         8.0       406882     247  1992
247                    Gandhi         8.0       228978     248  1982
248                  The Help         8.0       451922     249  2011
249      Beauty and the Beast         8.0       445750     250  1991

[250 rows x 5 columns]

In [ ]:
df.to_csv('TOP5Movies.csv')